### ISSUE TITLE
Can't use the bot (cannot finde module node_sqlite3.node)

### ISSUE THREAD

**Issue by guillefixx** [BenC14/Dumbledore#1]
Hi, I'm unable to use the bot. After doing `npm install` I tried the `BOT_API_KEY=MY_BOT_KEY node bin/bot.js` but then I get this error on the terminal:
> admins-iMac:Dumbledore guillermo$ BOT_API_KEY=MY_BOT_KEY node bin/bot.js
module.js:540
    throw err;
    ^
Error: Cannot find module '/Users/guillermo/Desktop/Dumbledore/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guillermo/Desktop/Dumbledore/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

I tried with node 8.1.2 and 8.9.3.

**Comment by BenC14** [comment]
So it looks like some of the dependencies are a bit out of date. You should try `rm -rf node_modules`  then `npm install` then `npm install sqlite3` then `npm install random-js` then run the bot. That worked for me on node 8.1.2. Hope that helps.

**Comment by guillefixx** [comment]
Well now the bot runs on my slack, but it seems it doesn't work. 

I invited the bot to a channel, I tried the "1 point to XXX" thing but nothing happens.
